import * as ts from 'typescript'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

interface Args {
  command: 'build' | 'watch' | 'help'
  dir: string
  out: string
}

const parseArgs = (argv: string[]): Args => {
  let command: Args['command'] = 'help'
  let dir = 'src/app'
  let out = '.nerv'
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === 'build' || arg === 'watch' || arg === 'help') command = arg
    else if (arg === '--dir') dir = argv[++i] ?? dir
    else if (arg === '--out') out = argv[++i] ?? out
  }
  return { command, dir, out }
}

const walk = (root: string, suffix: string, result: string[] = []): string[] => {
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const full = join(root, entry.name)
    if (entry.isDirectory()) walk(full, suffix, result)
    else if (entry.isFile() && entry.name.endsWith(suffix)) result.push(full)
  }
  return result
}

interface ClassInfo {
  name: string
  key: string
  deps: string[]
  file: string
}

const exportedClasses = (content: string): { name: string; deps: string[] }[] => {
  const source = ts.createSourceFile('service.ts', content, ts.ScriptTarget.Latest, true)
  const result: { name: string; deps: string[] }[] = []
  for (const stmt of source.statements) {
    if (!ts.isClassDeclaration(stmt) || !stmt.name) continue
    const exported = ts.getModifiers(stmt)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
    if (!exported) continue
    const ctor = stmt.members.find(ts.isConstructorDeclaration)
    const deps: string[] = []
    if (ctor) {
      for (const param of ctor.parameters) {
        const type = param.type
        if (type && ts.isTypeReferenceNode(type) && ts.isIdentifier(type.typeName)) {
          deps.push(type.typeName.text)
        }
      }
    }
    result.push({ name: stmt.name.text, deps })
  }
  return result
}

const classKey = (name: string): string => (name ? name[0]!.toLowerCase() + name.slice(1) : name)

const collectClasses = (dir: string): ClassInfo[] =>
  existsSync(dir)
    ? walk(dir, '.ts')
        .filter((file) => !file.endsWith('.routes.ts'))
        .flatMap((file) =>
          exportedClasses(readFileSync(file, 'utf8')).map(({ name, deps }) => ({
            name,
            key: classKey(name),
            deps,
            file,
          })),
        )
    : []

const sortClasses = (classes: ClassInfo[]): ClassInfo[] => {
  const byName = new Map(classes.map((c) => [c.name, c]))
  const state = new Map<string, 0 | 1>()
  const order: ClassInfo[] = []

  const visit = (name: string, trail: string[]): void => {
    const cls = byName.get(name)
    if (!cls) throw new Error(`nerv: unknown dependency "${name}"`)
    const s = state.get(name)
    if (s === 1) return
    if (s === 0) throw new Error(`nerv: circular dependency: ${[...trail, name].join(' → ')}`)
    state.set(name, 0)
    for (const dep of cls.deps) visit(dep, [...trail, name])
    state.set(name, 1)
    order.push(cls)
  }

  for (const cls of classes) visit(cls.name, [])
  return order
}

const hasRoutesExport = (content: string): boolean => {
  const source = ts.createSourceFile('routes.ts', content, ts.ScriptTarget.Latest, true)
  return source.statements.some((stmt) => {
    if (!ts.isVariableStatement(stmt)) return false
    const exported = ts.getModifiers(stmt)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
    if (!exported) return false
    const decl = stmt.declarationList.declarations[0]
    return !!decl && ts.isIdentifier(decl.name) && decl.name.text === 'routes'
  })
}

const hasConfigExport = (content: string): boolean => {
  const source = ts.createSourceFile('config.ts', content, ts.ScriptTarget.Latest, true)
  return source.statements.some((stmt) => {
    if (!ts.isVariableStatement(stmt)) return false
    const exported = ts.getModifiers(stmt)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
    if (!exported) return false
    const decl = stmt.declarationList.declarations[0]
    return !!decl && ts.isIdentifier(decl.name) && decl.name.text === 'config'
  })
}

const toPlatformPath = (path: string): string => path.split('\\').join('/')

const generate = (dir: string, out: string): string[] => {
  const matches = existsSync(dir)
    ? walk(dir, '.routes.ts').filter((file) => hasRoutesExport(readFileSync(file, 'utf8')))
    : []

  const lines = ['// auto-generated by nerv build — do not edit. Regenerate with `nerv build`.', '']
  if (matches.length) {
    lines.push(`import type { Route } from '${toPlatformPath(relative(out, 'src/router/factory.ts'))}'`)
    matches.forEach((file, i) => {
      lines.push(`import { routes as routes_${i} } from '${toPlatformPath(relative(out, file))}'`)
    })
    lines.push('')
    lines.push(`export const routes: Route[] = [${matches.map((_file, i) => `...routes_${i}`).join(', ')}]`)
  } else {
    lines.push('export const routes = [] as never[]')
  }
  return lines
}

const generateContainer = (dir: string, out: string): { lines: string[]; count: number } => {
  const classes = sortClasses(collectClasses(dir))
  const lines = ['// auto-generated by nerv build — do not edit. Regenerate with `nerv build`.', '']

  const byFile = new Map<string, string[]>()
  for (const cls of classes) {
    byFile.set(cls.file, [...(byFile.get(cls.file) ?? []), cls.name])
  }
  for (const [file, names] of byFile) {
    lines.push(`import { ${names.join(', ')} } from '${toPlatformPath(relative(out, file))}'`)
  }

  const configFile = join(dir, 'config.ts')
  const hasConfig = existsSync(configFile) && hasConfigExport(readFileSync(configFile, 'utf8'))
  if (hasConfig) {
    lines.push(`import { config } from '${toPlatformPath(relative(out, configFile))}'`)
  }

  const contextFile = join(dir, 'context.ts')
  const hasState = existsSync(contextFile)
  if (hasState) {
    lines.push(`import type { AppState } from '${toPlatformPath(relative(out, contextFile))}'`)
  } else {
    lines.push('export type AppState = Record<string, never>')
  }
  lines.push(`import { createRouteFactory } from '${toPlatformPath(relative(out, 'src/router/factory.ts'))}'`)
  lines.push('')

  if (classes.length) {
    lines.push('const buildContainer = () => {')
    for (const cls of classes) {
      lines.push(`  const ${cls.key} = new ${cls.name}(${cls.deps.map(classKey).join(', ')})`)
    }
    lines.push(`  return { ${classes.map((c) => c.key).join(', ')} }`)
    lines.push('}')
    lines.push('')
    lines.push(`export const container = ${hasConfig ? `{ ...buildContainer(), config }` : 'buildContainer()'}`)
  } else {
    lines.push(`export const container = ${hasConfig ? '{ config }' : '{}'}`)
  }
  lines.push('')
  lines.push('export type AppDeps = typeof container')
  lines.push('')
  lines.push('export const appRoute = createRouteFactory<AppDeps, AppState>()')
  return { lines, count: classes.length }
}

const build = (dir: string, out: string): void => {
  mkdirSync(out, { recursive: true })
  const routesLines = generate(dir, out)
  writeFileSync(join(out, 'routes.gen.ts'), routesLines.join('\n') + '\n')
  const { lines: containerLines, count } = generateContainer(dir, out)
  writeFileSync(join(out, 'container.gen.ts'), containerLines.join('\n') + '\n')
  const routeCount = routesLines.filter((line) => line.startsWith('import { routes as')).length
  console.log(`nerv build: routes.gen.ts (${routeCount} files), container.gen.ts (${count} services)`)
}
const main = (): void => {
  const { command, dir, out } = parseArgs(process.argv.slice(2))
  if (command === 'help') {
    console.log('nerv <build|watch> [--dir src/app] [--out .nerv]')
    return
  }
  if (command === 'build') {
    try {
      build(dir, out)
    } catch (error) {
      console.error(error instanceof Error ? error.message : error)
      process.exitCode = 1
    }
    return
  }
  if (command === 'watch') {
    try {
      build(dir, out)
    } catch (error) {
      console.error(error instanceof Error ? error.message : error)
    }
    console.log(`nerv watch: watching ${dir} for changes (Ctrl+C to stop)`)
    const timer = setInterval(() => {
      if (!existsSync(dir)) return
      const current = generate(dir, out).join('\n')
      const previous = existsSync(join(out, 'routes.gen.ts')) ? readFileSync(join(out, 'routes.gen.ts'), 'utf8') : ''
      if (current !== previous) build(dir, out)
      try {
        generateContainer(dir, out)
      } catch {
        // report container errors on next cycle
      }
    }, 500)
    process.on('SIGINT', () => {
      clearInterval(timer)
      process.exit(0)
    })
  }
}
main()
