import * as ts from 'typescript'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

interface Args {
  command: 'build' | 'watch' | 'help'
  dir: string
  out: string
}

const parseArgs = (argv: string[]): Args => {
  let command: Args['command'] = 'help'
  let dir = 'src/app'
  let out = '.nerv'
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === 'build' || arg === 'watch' || arg === 'help') command = arg
    else if (arg === '--dir') dir = argv[++i] ?? dir
    else if (arg === '--out') out = argv[++i] ?? out
  }
  return { command, dir, out }
}

const walk = (root: string, result: string[] = []): string[] => {
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const full = join(root, entry.name)
    if (entry.isDirectory()) walk(full, result)
    else if (entry.isFile() && entry.name.endsWith('.routes.ts')) result.push(full)
  }
  return result
}

const hasRoutesExport = (content: string): boolean => {
  const source = ts.createSourceFile('routes.ts', content, ts.ScriptTarget.Latest, true)
  return source.statements.some((stmt) => {
    if (!ts.isVariableStatement(stmt)) return false
    const exported = ts.getModifiers(stmt)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
    if (!exported) return false
    const decl = stmt.declarationList.declarations[0]
    return !!decl && ts.isIdentifier(decl.name) && decl.name.text === 'routes'
  })
}

const toPlatformPath = (path: string): string => path.split('\\').join('/')

const generate = (dir: string, out: string): string[] => {
  const matches = existsSync(dir) ? walk(dir).filter((file) => hasRoutesExport(readFileSync(file, 'utf8'))) : []

  const lines = ['// auto-generated by nerv build — do not edit. Regenerate with `nerv build`.', '']
  if (matches.length) {
    lines.push(`import type { Route } from '${toPlatformPath(relative(out, 'src/router/factory.ts'))}'`)
    matches.forEach((file, i) => {
      lines.push(`import { routes as routes_${i} } from '${toPlatformPath(relative(out, file))}'`)
    })
    lines.push('')
    lines.push(`export const routes: Route[] = [${matches.map((_file, i) => `...routes_${i}`).join(', ')}]`)
  } else {
    lines.push('export const routes = [] as never[]')
  }
  return lines
}

const build = (dir: string, out: string): void => {
  mkdirSync(out, { recursive: true })
  const lines = generate(dir, out)
  writeFileSync(join(out, 'routes.gen.ts'), lines.join('\n') + '\n')
  const count = lines.filter((line) => line.startsWith('import { routes as')).length
  console.log(`nerv build: .nerv/routes.gen.ts written (${count} route files)`)
}

const main = (): void => {
  const { command, dir, out } = parseArgs(process.argv.slice(2))
  if (command === 'help') {
    console.log('nerv <build|watch> [--dir src/app] [--out .nerv]')
    return
  }
  if (command === 'build') {
    build(dir, out)
    return
  }
  if (command === 'watch') {
    build(dir, out)
    console.log(`nerv watch: watching ${dir} for changes (Ctrl+C to stop)`)
    const timer = setInterval(() => {
      if (!existsSync(dir)) return
      const current = generate(dir, out).join('\n')
      const previous = existsSync(join(out, 'routes.gen.ts')) ? readFileSync(join(out, 'routes.gen.ts'), 'utf8') : ''
      if (current !== previous) build(dir, out)
    }, 500)
    process.on('SIGINT', () => {
      clearInterval(timer)
      process.exit(0)
    })
  }
}

main()
